version: "3.9"
name: bettingslip
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sqlserver
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - SA_PASSWORD=m8A2T£5oH4n
    ports:
      - "5003:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P m8A2T£5oH4n -Q \"SELECT 1\""]
      interval: 10s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"   # RabbitMQ default port for clients
      - "15672:15672" # RabbitMQ management UI

  bettingslip.service:
    image: bettingslipservice
    build:
      context: .
      dockerfile: src/BettingSlip.Service/Dockerfile
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=BettingSlipDb;User Id=sa;Password=m8A2T£5oH4n;TrustServerCertificate=True;
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
    ports:
      - "5001:5001"
      - "5002:5002"
  wallet.service:
    image: walletservice
    build:
      context: .
      dockerfile: /src/BettingSlip.WalletService/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_started
    environment:
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
    ports:
      - "5011:5011"
      - "5012:5012"

volumes:
  sqlserver-data: